### ISSUE TITLE
Panic in lewton::audio::floor_decode on malformed input

### ISSUE THREAD

**Issue by Shnatsel** [RustAudio/lewton#44]
Error message: `'index out of bounds: the len is 42 but the index is 128'`

Command to reproduce the crash: 
`RUSTFLAGS='--cfg=fuzzing' cargo run --release --example perf /path/to/testcase` 

Tested on commits 2c644693f6456d9ae91e47cc5e38603d21885985 and 0d13bc4a774868d4e55a56568b51339367fb0584, reproducible on both. Found using [afl.rs](https://github.com/rust-fuzz/afl.rs)

I'm sorry I keep breaking your stuff :sweat_smile:

**Comment by Shnatsel** [comment]
Forgot the test samples: 
[yet-another-oor.zip](https://github.com/RustAudio/lewton/files/2907368/yet-another-oor.zip)

**Comment by BenSandeen** [comment]
I think I'm gonna take a stab at this if no one else is

**Comment by est31** [comment]
Commit 907806061e9ca620de3ee4b3684f05e34fd276c6 has fixed the issue itself, all that remains is addition of a testcase.

**Comment by est31** [comment]
Ok these are the repacked files:

* [bug-44-sample059.ogg.zip](https://github.com/RustAudio/lewton/files/2922511/bug-44-sample059.ogg.zip)

* [bug-44-sample060.ogg.zip](https://github.com/RustAudio/lewton/files/2922512/bug-44-sample060.ogg.zip)

Only took the first two because I think the bug is not very tricky in itself.
